### ISSUE TITLE
Login only one time

### ISSUE THREAD

**Issue by zeeshan774r** [Codeception/CodeceptJS#1166]
I have written login function in steps_file.js,I have different folder in which different files where test cases are written.It takes so much time in running all test bcoz in every folder for each file login happens first so each test taking almost 10-12 sec and i have almost 70-80 test cases in all.how to reduce time for test cases such that login happen only once.

**Comment by austinmehmet** [comment]
Could you not just use the BeforeSuite hook? I assume you have some kind of a helper to log you in so you could probably do something like the following:

```
BeforeSuite((I) => {
  I.login()
});
```

**Comment by astanciu** [comment]
According to the docs, `BeforeSuite` has access to `I` but not the browser object at that stage.

I too would like to know how to achieve this.  
- Logging in a `Before` takes up too much time, as OP mentioned
- Trying to be smart in a `Before` and manually `setCookie` does not work since you have to be on a page to set the cookie
- using `restart` with `keepCookies` would work but how do we ensure that the first scenario that runs is the one that does the login?

**Comment by GSasu** [comment]
You can set keepBrowserState and keepCookies to true to maintain state from test to another. The login can be done in a before hook.

**Comment by PeterNgTr** [comment]
https://codecept.io/plugins/#autologin would help!
