### ISSUE TITLE
Documentation for SelectOption is missing

### ISSUE THREAD

**Issue by pavel-mailpoet** [Codeception/CodeceptJS#2053]
#### What are you trying to achieve?

I am trying to see the documentation for SelectOption here: https://codecept.io/helpers/WebDriverIO#selectoption
#### What do you get instead?

There is no documentation. It seems like it should be there, but some generator went wrong:
![Screenshot 2019-11-26 at 13 10 19](https://user-images.githubusercontent.com/29194603/69631378-1ee46700-104e-11ea-8558-ce3672ec3a22.png)

**Comment by PeterNgTr** [comment]
The WebDriverIO (wdio v4) helper should be deprecated. Trying to use the WebDriver (wdio v5) helper instead.

**Comment by pavel-mailpoet** [comment]
I got to this page from search, there is no other WebDriver option there, or am I missing something?

![Screenshot 2019-11-26 at 15 04 37](https://user-images.githubusercontent.com/29194603/69640128-214ebd00-105e-11ea-87c3-00009a0e5c0c.png)

**Comment by mirao** [comment]
Yes, recently I was also confused that search in documentation refers to WebDriverIO instead of expected WebDriver when searching methods.
So you get https://codecept.io/helpers/WebDriverIO#selectoption (with no useful info) instead of https://codecept.io/helpers/WebDriver#selectoption (where correct info about `I.selectOption()` is)

**Comment by mirao** [comment]
It seems to be fixed with the latest update of website (CC: @DavertMik ).
The page https://codecept.io/helpers/WebDriverIO no more exists

**Comment by Vorobeyko** [comment]
Yes. This issue is resolved. 
Please, see - https://codecept.io/helpers/WebDriver/#selectoption
