### ISSUE TITLE
can we save the passed test case  screenshot automatic

### ISSUE THREAD

**Issue by tony204** [Codeception/CodeceptJS#281]
now we need to write I. savescreenshot to save the screenshot on the every test case.  So can we save the passed test case screenshot automatic?

**Comment by DavertMik** [comment]
I think you can develop a custom [Helper](http://codecept.io/helpers/) which will do this. You can use `_after` hook, access the WebDriveIO || Protractor || Nightmare and call `saveScreenshot`:

```js
_after() {
    this.helpers['WebDriverIO'].saveScreenshot(name);
}
```

**Unfortunately** due to technical reasons there is no good way to obtain test name inside a Helper :( So you can store it globally or generate a unique names for screenshots...

Anyway, what you ask for is a customization which can't be a built in feature.
