### ISSUE TITLE
How to perform conditional execution of tests 

### ISSUE THREAD

**Issue by adityamertia** [Codeception/CodeceptJS#296]
How do i check for conditional statements in CodeceptJS testcase. There is no documentation to suggest a way to achieve this.
E.g 
I.amOnPage('www.gmail.com');
check for cookies set. 
If (cookies are set) 
    then goto 'https://mail.google.com/mail/u/0/#inbox' 
else
    check for login password elements and click login.

Is there a recommended way to achieve conditional executions of test workflows?

Thanks
Aditya

**Comment by DavertMik** [comment]
To be honest it's a bad idea to have test cases like this. If you are not sure how the test would behave they are not reliable. If you run test locally and test passes, then crashes on CI server, and you can debug that for ages just because test takes a different path. Sure, you can use `if` conditionals inside of a test:

```
let cookie = yield I.grabCookie('auth');
if (cookie.value) {
   I.amOnPage('http://google.com');
   // ....
}
```

I also won't recommend you to check emails using GMail web interface. It makes test fragile even more. I recommedn to install [Maildev](https://www.npmjs.com/package/maildev) for handling received emails. You can use RETS api or Web interface to check if email was delivered.

**Comment by adityamertia** [comment]
Thanks for the reply @DavertMik. I am trying to develop web automation and not a test case. Wanted to use codecept for the same. In doing so i have no control on how the workflow of a site will behave. This is similar to webscraping where i login to a website and scrap the site by clicking through....grabbing a link and table element, run through all the table elements and fetch data. Is it still a bad idea? I am not sure then if codecept is the right tool or not?

Thanks

**Comment by DavertMik** [comment]
>  Is it still a bad idea? I am not sure then if codecept is the right tool or not?

well, depends on your task. CodeceptJS fits well for scenario driven tests, if you don't have somehting like scenarios but you try to scrap everything you need, that probably make you slower. I think you can try a simpler tool with more control like `webdriverio` also you may try a tool from another language in order to not deal with asyncs and promises.
