### ISSUE TITLE
Discrepancies between code documentation online and the NPM package

### ISSUE THREAD

**Issue by pooventhan** [Codeception/CodeceptJS#3324]
Hi there!
I noticed some discrepancies with the code documentation online and the NPM package.
The [web documentation](https://codecept.io/helpers/WebDriver/#waitforvisible) says `waitForVisible` method returns a promise and the [source file](https://github.com/codeceptjs/CodeceptJS/blob/3.2.3/lib/helper/WebDriver.js#L2234) is an async method.
However, the types.d.ts file (from the NPM package) says it is a void method. 

Is it a bug in .d.ts file ?

![image (17)](https://user-images.githubusercontent.com/35288391/171325125-3a885313-10b7-4138-b0e3-668b978bd74b.png)

### Details
* CodeceptJS version: 3.2.3
* NodeJS Version: v16.13.1
* Operating System: Windows 10

**Comment by kobenguyent** [comment]
I guess so @pooventhan as this method doesn't return anything.

**Comment by fwouts** [comment]
This appears to be caused by various mustache templates having the wrong return type, i.e. `void` instead of `Promise<void>` such as:
https://github.com/codeceptjs/CodeceptJS/blob/f598059451c6c54c7a49c31ff6b2958cde23ee4a/docs/webapi/amOnPage.mustache#L11

There are also dozens of mustache templates where a promise return type is documented in English, but not in JSDoc, such as:
https://github.com/codeceptjs/CodeceptJS/blob/f598059451c6c54c7a49c31ff6b2958cde23ee4a/docs/webapi/scrollTo.mustache#L12

Would you like me to prepare a PR to fix this?

**Comment by kobenguyent** [comment]
> This appears to be caused by various mustache templates having the wrong return type, i.e. `void` instead of `Promise<void>` such as:
> 
> https://github.com/codeceptjs/CodeceptJS/blob/f598059451c6c54c7a49c31ff6b2958cde23ee4a/docs/webapi/amOnPage.mustache#L11
> 
> 
> 
> There are also dozens of mustache templates where a promise return type is documented in English, but not in JSDoc, such as:
> 
> https://github.com/codeceptjs/CodeceptJS/blob/f598059451c6c54c7a49c31ff6b2958cde23ee4a/docs/webapi/scrollTo.mustache#L12
> 
> 
> 
> Would you like me to prepare a PR to fix this?

That'll be great @fwouts
