### ISSUE TITLE
Update Faker-js version to 7.6.0 in package.json of codecept currently it is 5.5.3 and it is having some issue with typescript.

### ISSUE THREAD

**Issue by vyasmayur** [Codeception/CodeceptJS#3498]
#### What are you trying to achieve?
Update Faker-js version to 7.6.0 in package.json of codecept currently it is 5.5.3 and it is having some issue with typescript.
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.
Getting below error :
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: XXX-codecept@1.0.0
npm ERR! Found: @faker-js/faker@7.6.0
npm ERR! node_modules/@faker-js/faker
npm ERR!   peer @faker-js/faker@"^7.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @faker-js/faker@"^5.5.3" from codeceptjs@3.3.6
npm ERR! node_modules/codeceptjs
npm ERR!   codeceptjs@"^3.3.6" from the root project
npm ERR!   peer codeceptjs@">= 2.3.3" from @codeceptjs/configure@0.10.0
npm ERR!   node_modules/@codeceptjs/configure
npm ERR!     @codeceptjs/configure@"^0.10.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.3.6
* NodeJS Version: 8.15.0
* Operating System: Mac OS
* puppeteer || webdriverio || testcafe version (if related) : Playwright.
* Configuration file:

```js
# paste config here
```

**Comment by Hristovski** [comment]
a workaround for this is using --force like: `npm i @faker-js/faker --force`
but it's just a temporary workaround

**Comment by mirao** [comment]
I hit the same issue

**Another workaround:**

- Use a custom version of `faker-js` this way
- Put `"faker-js": "npm:@faker-js/faker@^7.6.0"` into `devDependencies` in your project's `package.json` and run `npm ci`

The issue seems to be fixed in CodeceptJS 3.3.7 where the peer dependency was removed: https://github.com/codeceptjs/CodeceptJS/commit/a22f7632904dce0f47b0fa1c64402ff9dc0e0f97#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519. Now I'm able to install `npm i @faker-js/faker@^7.6.0` without any problems.
