### ISSUE TITLE
[ Question ] How to get babel working to support imports?

### ISSUE THREAD

**Issue by jhartma** [Codeception/CodeceptJS#370]
#### What are you trying to achieve?
I want to use es2015 import syntax

#### What do you get instead?
I tried the ```--compilers js:babel-core/register``` option which works fine with mocha, but I get a console error ```Unexpected token import```

```bash
SyntaxError:                                                                                             
    at Object.exports.runInThisContext (vm.js:78:16)                                                     
    at Module._compile (module.js:543:28)                                                                
    at Object.Module._extensions..js (module.js:580:10)                                                  
    at Module.load (module.js:488:32)                                                                    
    at tryModuleLoad (module.js:447:12)                                                                  
    at Function.Module._load (module.js:439:3)                                                           
    at Module.require (module.js:498:17)                                                                 
    at require (internal/module.js:20:19)                                                                
    at .../node_modules/codeceptjs/node_modules/mocha/lib/mocha.js:222:27
```

#### Details
* CodeceptJS version: 0.4.13
* NodeJS Version: 7.4.0
* Operating System: Linux (Arch)

**Comment by DavertMik** [comment]
Sorry, babel is not supported as well as any other compilers. I hope at some point NodeJS will implement imports natively.

Probably some support of transpilers can be implemented but I don't think I will do it in nearest future. Working with native code has its benefits.

**Comment by sfedorin** [comment]
Hi,
The same question for me... I tried to set packages
```
{
  "name": "portal",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "npx codeceptjs run --steps"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/cli": "^7.8.3",
    "@babel/core": "^7.8.3",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-export-default-from": "^7.8.3",
    "@babel/polyfill": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@babel/preset-react": "^7.8.3",
    "@babel/register": "^7.8.3",
    "@codeceptjs/mailslurp-helper": "^1.0.2",
    "codeceptjs": "^2.3.6",
    "puppeteer": "^2.0.0",
    "mailslurp-client": "^6.7.3"
  }
}
```
.babelrc file has beed added as well. But I still get error `SyntaxError: Cannot use import statement outside a module`

**Comment by evasyuk** [comment]
You are not allowed to use "import" in your test scripts, but you still can require files with "import" command by adding babel transpiler

In my case it was about implementing grey-box testing: I need to use already existing api-interaction files with ES6 => no option to change basic code just to bypass (poor) codecept engine implementation

How to reproduce my experience:
1. create ".babelrc" file
- make sure that it works fine. in order to do this you need to create 2 test files:
-- one is using "require" commands only
-- another contains some "import" instruction

<img width="1497" alt="test" src="https://user-images.githubusercontent.com/4641605/74017685-5734e980-499d-11ea-9289-84122bc74972.png">

<img width="1618" alt="test2" src="https://user-images.githubusercontent.com/4641605/74017700-5b610700-499d-11ea-802b-5945a9b6260c.png">


<img width="1642" alt="apiIImports" src="https://user-images.githubusercontent.com/4641605/74017713-5f8d2480-499d-11ea-9d15-2c84735f48f4.png">


2. once babel settings are OK, use it your "steps_file.js" or even tests


<img width="1660" alt="actualImport" src="https://user-images.githubusercontent.com/4641605/74017719-63b94200-499d-11ea-91b3-39fc3dc7486f.png">
