### ISSUE TITLE
Capture the network activity of an http request in HAR format using CodeceptJS

### ISSUE THREAD

**Issue by magimenon** [Codeception/CodeceptJS#413]
#### What are you trying to achieve?
I'm working on getting the HAR report for the webpage I'm testing. This works with the help of "nightmare-har-plugin" using NightmareJS. I'm trying to use codeceptJS and looks like codeceptJS doesn't have the option to get the HAR. Is it something which the team will add in the near future?

Below is my code.
Scenario("Functional Test HomePage", function () {

	 har.install(Nightmare);
	 var nightmare = Nightmare(Object.assign(har.getDevtoolsOptions(), options));
	 nightmare.waitForDevtools()
		 .goto("http://www.google.com")
		 .getHAR()
		 .end()
		 .then(function (result) {
			 console.log(result)
		 })
		 .catch(function (error) {
		    console.error(error);
	    });
 });

**Comment by DavertMik** [comment]
> Is it something which the team will add in the near future?

Actyally not, but you can help us by making a Pull Request. To be honest I don't even know anything about the HAR format and its use ceases for testing.
I think you can create a custom Helper which extends from Nigthmare and implement that method there. 

From what I see the problem here is to provide a way to install Nightmare plugins withink CodeceptJs
