### ISSUE TITLE
puppeteer from 22.0.0 will remove $x and waitForXpath

### ISSUE THREAD

**Issue by incoming-th** [Codeception/CodeceptJS#4198]
Hi,

Just to inform about this breaking change:

https://github.com/puppeteer/puppeteer/pull/11782

So far I believe only 5 places needs to be changed in the Puppeteer helper (1 for $x and 4 for waitForXpath):

![image](https://github.com/codeceptjs/CodeceptJS/assets/26375917/e324c8ca-b78f-472e-a6ad-857236c2c18f)

![image](https://github.com/codeceptjs/CodeceptJS/assets/26375917/0b5435e8-0292-4a4c-a90f-ce4c63950c7d)

Please close if this is already known or if no impact.

Thanks.

**Comment by adrien-flyfish** [comment]
We were forced to upgrade to Puppeteer v22 because there was an issue with downloaded dependencies with chrome/chromedrvier from what we could see. Upgrading to Puppeteer v22 fixed that issue, but broke our tests because we relied heavily on `waitForXpath`

I haven't seen any PR for a fix for this as yet, so we did a very Quick and Dirty workaround for now until it is fixed by Codecept:

In your `codecept.conf.js` file, add the following code above the `exports.config = {` line:
```
const fs = require('fs');

(function() {
  const codeceptWdioPlugin = `${process.cwd()}/node_modules/codeceptjs/lib/helper/Puppeteer.js`;
  console.log(`Fixing CodeceptJS's puppeteer helper file at ${codeceptWdioPlugin}`);
  if (!fs.existsSync(codeceptWdioPlugin)) {
    throw new Error(`Unable to find CodeceptJS's CodeceptJS's puppeteer helper file at ${codeceptWdioPlugin}`);
  }
  let codeceptWdioPluginContent = fs.readFileSync(codeceptWdioPlugin, 'utf8');
  if (codeceptWdioPluginContent.match(/^\/\/updated/)) {
    return;
  }
  codeceptWdioPluginContent = codeceptWdioPluginContent.replace(/^/, '//updated\n');
  codeceptWdioPluginContent = codeceptWdioPluginContent.replace(/context.waitForXPath\(locator.value,/g, 'context.waitForSelector(`::-p-xpath(${locator.value})`,');

  fs.writeFileSync(codeceptWdioPlugin, codeceptWdioPluginContent, 'utf8');
})();
```

We found that v22 of Puppteer wanted to use `waitForSelector()` and requires `::-p-xpath()` 
https://pptr.dev/guides/query-selectors/#xpath-selectors--p-xpath

This fix seems to work for now, but once Codecept release a fix, its probably best to bin this code!
