### ISSUE TITLE
setCookie() timed out

### ISSUE THREAD

**Issue by bendiggle** [Codeception/CodeceptJS#552]
#### What are you trying to achieve?
I am trying to set a cookie in my tests `I.setCookie({name: 'cookieName', value: 'cookieValue})'`

#### What do you get instead?
I get this following error: `Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?`

* CodeceptJS version: 0.6.3
* NodeJS Version: 8

**Comment by APshenkin** [comment]
@bendiggle Can you please provide more information. What helper do you use? Logs in verbose mode will be very helpfull

**Comment by bendiggle** [comment]
Hi @APshenkin thanks for getting back to me. I wasn't actually using it correctly as I was trying to set the cookie before going to a page.
However I have a new issue that hopefully you can help me with. 
I am using the Nightmare helper. I am trying to set a cookie which will allow me to bypass a login screen in my app. The cookie is being set as I can see it when I use Nightmares `cookies.get()`. However, the cookie is not in the request in my app and therefore cannot get passed the login screen when it checks for the cookie.
Any ideas?

**Comment by APshenkin** [comment]
@bendiggle I will describe how I solved the same problem as you:
My test code was like this:
```
let token = yield I.getToken(login, password);
I.amOnPage('/404');
I.setCookie({name: 'auth', value: token})
I.amOnPage('/');
```

This will allow you to open main page and bypass a login screen. I recommend to get auth token via API using sync-request library if it's possible (or get it from DB directly etc.), because this will give you 100% guarantee, that problems in tests will not be associated with login screen (other way you can try to get cookie during your tests, but it may causes problems, if you have any issue on login screen)

**Comment by bendiggle** [comment]
@APshenkin I tried that previously but just by hard coding an up-to-date token. However, the issue I'm having is that in my app I am using express. So when my app goes to check for the cookie in the request, the cookie is an empty object and therefore not able to go passed the login. On the other hand, if in my tests I do getCookie and log out the response, the cookie exists. 
Thanks for the help!
