### ISSUE TITLE
Can you please tell me how can i take user input as number while running the automation.

### ISSUE THREAD

**Issue by tvinerkar** [Codeception/CodeceptJS#613]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by willcooley** [comment]
If you are talking about getting a value from the input during a test, you can yield the value out, and use an assert library to test or something.

**Comment by APshenkin** [comment]
@tvinerkar Please provide more information about your problem. Code examples, codeceptJS config, test page description will be useful.

FYI in next release we will add `waitForValue` method for WebdriverIO, you will be able to use it to validate that value appears in input. Also as @willcooley mentioned, you can use `grabValueFrom` to take input value

**Comment by tvinerkar** [comment]
The scenario is when we try to login gmail using 2 step verification we get an authentication number. That process i need to complete.

**Comment by APshenkin** [comment]
@tvinerkar I can propose several ways:
1. Disable 2 step verification on your account. I don't think that you guys are from google and you need to test google 2 step verification service
2. Create reserve codes and use them in your tests. This is not a good option, because these codes will always come to an end
3. Test this on Android with Authenticator app. Then you will be able switch to the Authenticator app an get this code.

But I still think that you have just disable 2 step verification. Why You need this? Maybe some additional information will give me opportunity to propose other solutions

**Comment by DavertMik** [comment]
@tvinerkar if you need to do some manual steps, you can use `pause()` function inside a test. Then you can perform authentication or whatever you need and then press Enter to continue. 

`pause()` works only in debug mode, so add `--debug` when running
