### ISSUE TITLE
How to verify list item from DropDown List by Codeceptjs

### ISSUE THREAD

**Issue by anhvuong123** [Codeception/CodeceptJS#766]
Hi everyone,

Please help me via the case to verify all item value from a specific DropDown list as real user see on the Browser.
I've tried the code: 
Step1: I.click("dropdowlistLocator");
==> then dropdown list open to list all items
Step2: I.see("dropdowlistLocator","textForVerify") //
==> but dropdownlist always off & not show the list as Step1. So, I can't get the test via the code above
Please help me via the case. If you have any the way to get real item from dropdown list, please let me know about that.

Thanks,

**Comment by jploskonka** [comment]
Have you tried using `I.waitForText` instead of `I.see`? With what you provided I'd guess that your dropdown may have some kind of delay (maybe some fancy transition, maybe waiting for some request in the background) and `I.see` expectation is just executed before dropdown is actually visible. Especially if you're using Nightmare as backend it's quite common case.

If this won't help then please provide more info about your use case like codecept config, what backend are you using etc. :)

**Comment by anhvuong123** [comment]
Thank jploskonka for your suggestion, it works well for me now
