### ISSUE TITLE
How To Close Only Those Chrome Windows That Has Been Open By Automation tests.

### ISSUE THREAD

**Issue by ninpop25** [Codeception/CodeceptJS#864]
#### not able to find any method on how to do so

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:window 10
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by ninpop25** [comment]
@APshenkin @DavertMik : Please look into this and also please let me know that how to Run more then 1 tests with single command

**Comment by reubenmiller** [comment]
Personally I have never had an issue with this, though it could be because I am using a different chrome.exe just for the tests.

You can specify the chrome.exe to use in the tests in the codeceptjs configuration file (I like to the a .js file for the config because you can do some dynamic assignments instead of having everything statically defined).

Look at the `desiredCapabilities.chromeOptions.binary` setting.

```js
exports.config = {
    output: './output',
    helpers: {
        WebDriverIO: {
            url: process.env.URL || 'http://192.168.8.101',
            browser: process.env.BROWSER || 'chrome',
            restart: false,
            keepCookies: true, // Keep cookies if the browser is not restarting between tests
            desiredCapabilities: {
                unexpectedAlertBehaviour: 'ignore',
                firefox_binary: config.get('test:use_system_browser') ? '' : config.get('browser:firefox_binary'),
                chromeOptions: {
                    // Set path to the chrome binary you want to use.
                    binary: 'C:\\Users\\MillerR\\Desktop\\chrome64_57.0.2987.133\\chrome.exe',

                    // disable "chrome is being controlled by automated software"
                    args: ['disable-infobars=true'],
                },
            },
        },
        FileSystem: {},
    },
    mocha: {},
    bootstrap: false,
    teardown: null,
    hooks: [],
    tests: './tests/*_test.js',
    timeout: 10000,
    name: 'doler-js',
};
```

Now that you can specify the `chrome.exe` binary path, then you probably need an independent version of chrome. Fortunately there is a great website where you can download older versions of chrome in a standalone format [here](https://www.slimjet.com/chrome/google-chrome-old-version.php)

**Comment by ninpop25** [comment]
Thanks @reubenmiller
