### ISSUE TITLE
GrabBrowserLogs Showing Previous Logs Even After Clearing The Console

### ISSUE THREAD

**Issue by ninpop25** [Codeception/CodeceptJS#876]
#### I am running Automation test cases on Server Machine (Windows 10) Via Jenkins and all I want is that when I load my test page then I click on some button and that after that click action on button records some log in console in(Info) and I want to check the occurrence and count of that log.

@APshenkin @DavertMik @BLouzada : Please help me in this

Issue is that when I load my test page,I have used console.clear(); in I.ExecuteScript(); of codeceptjs and after that I click on Button and after that I am using GrabBrowserLogs(); and print the log..but the printed values are not the one that should come after click on Button but its the default one before even using console.clear(),I mean as per me when my test page loads then only the GrabBrowserLogs(); records the log and give me result,its not getting cleared after using console.clear()

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// templatePage.openTemplateDirect("FVAutomation%2345670");
    I.waitForVisible({ xpath: '//input[@data-fv-xd-ctrlid="btnPeoplePickers"]' }, 60);
    I.executeScript(function () {
        console.clear();
    });
      
    I.click({ xpath: '//input[@data-fv-xd-ctrlid="btnPeoplePickers"]' });
    let logs = yield I.grabBrowserLogs();
    console.log(JSON.stringify(logs))
});

```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by reubenmiller** [comment]
Unfortunately this is just how the WebDriver.io api works. I believe the logs retrieved by the I.grabBrowserLogs (i.e. [webdriver.io api](http://webdriver.io/api/protocol/log.html)), will only be cleared when the I.grabBrowserLogs is called.

So if you want to clear the log, then just call I.grabBrowserLogs() instead of using the `I.executeScript` function.

It is not ideal, but just the way things are. The browser logs is not part of the webdriver specification, so different tools handle it differently.

**Comment by reubenmiller** [comment]
So I think we can close this issue as it is more an issue/quirk with webdriver.io and not Codeceptjs itself.

**Comment by ninpop25** [comment]
@reubenmiller : thanks :)
