### ISSUE TITLE
Breach of semver

### ISSUE THREAD

**Issue by callumlocke** [Codeception/CodeceptJS#883]
- codeceptjs `1.0.x` requires Node `>=6.11`
- codeceptjs `1.1.x` requires Node `>=8.9.1`

I think changing the engine requirement counts as a breaking change, so it should have been a major version bump (2.0.0) according to [semver.org](https://semver.org/).

The easiest solution would be to republish as 2.0.0, and mark 1.1.x as deprecated in npm.

**Comment by DavertMik** [comment]
> I think changing the engine requirement counts as a breaking change, so it should have been a major version bump (2.0.0) according to semver.org.

> MAJOR version when you make incompatible API changes,

We didn't make any incompatible API changes... We updated the requirements without changing API.

Also, Node 6 is not recommended for current usage and is now in maintenance mode. 

Yes, we had this debate should it be 1.1 or 2.0 but bumping version this way would prevent ^1.0 users to upgrade without changing their requirements in package.json. It doesn't make any sense because the upgrade doesn't introduce API breaks.
