### ISSUE TITLE
Mochawesome helper does not work with shell command

### ISSUE THREAD

**Issue by mingfang** [Codeception/CodeceptJS#896]
#### What are you trying to achieve?
I'm trying to run the shell command

#### What do you get instead?
The shell command is not working.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
 ./node_modules/codeceptjs/bin/codecept.js shell --verbose
String interactive shell for current suite...
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook Nightmare._beforeSuite()
   [1] Queued | hook Mochawesome._beforeSuite()
   Emitted | test.before
   [1] Queued | hook Nightmare._before()
   [1] Queued | hook Mochawesome._before()
   [1] Queued | Start new session
   [1] Queued | () => event.emit(event.test.after)
   [1] Queued | () => event.emit(event.suite.after, {})
   [1] Queued | () => codecept.teardown()
 > [Session] Starting singleton browser session
(node:15157) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'currentTest' of undefined
(node:15157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Details

* CodeceptJS version: 1.1.2
* NodeJS Version: 8.9.4
* Operating System: OSX
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:
```"helpers": {
    "Nightmare": {
    },
    "Mochawesome": {
      "uniqueScreenshotNames": "true"
    }
  }
```

The problem appears to be _beforeSuite(suite) is getting suite = {} (empty object)

**Comment by reubenmiller** [comment]
Yeah I can confirm this bug. It looks like there is a problem when the shell is launched from the command line and the Mochawesome helper is used/defined. The problem is that the _before() hook in the Mochawesome Helper is expecting a test scenario, and there is no null checking.

We can probably get a PR fairly quick, though in the meantime you can just create a dummy Scenario and call the `debug()` function. The debug() function allows you to call up the interactive shell within a scenario (great for debugging!)

**Comment by mingfang** [comment]
@reubenmiller the ```debug()``` is a nice trick to know. Thanks.
